//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComAssistant.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComAssistant.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add COM port debugging 的本地化字符串。
        /// </summary>
        public static string Add_COM_Port_Debugging {
            get {
                return ResourceManager.GetString("Add_COM_Port_Debugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Baud Rates: 的本地化字符串。
        /// </summary>
        public static string COM_BAUD_RATES {
            get {
                return ResourceManager.GetString("COM_BAUD_RATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect 的本地化字符串。
        /// </summary>
        public static string COM_CONNECT {
            get {
                return ResourceManager.GetString("COM_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Connected) 的本地化字符串。
        /// </summary>
        public static string COM_CONNECTED {
            get {
                return ResourceManager.GetString("COM_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataBits: 的本地化字符串。
        /// </summary>
        public static string COM_DATA_BITS {
            get {
                return ResourceManager.GetString("COM_DATA_BITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect 的本地化字符串。
        /// </summary>
        public static string COM_DISCONNECT {
            get {
                return ResourceManager.GetString("COM_DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encoding: 的本地化字符串。
        /// </summary>
        public static string COM_ENCODING {
            get {
                return ResourceManager.GetString("COM_ENCODING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Not Connected) 的本地化字符串。
        /// </summary>
        public static string COM_NOT_CONNECTED {
            get {
                return ResourceManager.GetString("COM_NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parity: 的本地化字符串。
        /// </summary>
        public static string COM_PARITY {
            get {
                return ResourceManager.GetString("COM_PARITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port: 的本地化字符串。
        /// </summary>
        public static string COM_PORT_NAME {
            get {
                return ResourceManager.GetString("COM_PORT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StopBits: 的本地化字符串。
        /// </summary>
        public static string COM_STOP_BITS {
            get {
                return ResourceManager.GetString("COM_STOP_BITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string LANG {
            get {
                return ResourceManager.GetString("LANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History 的本地化字符串。
        /// </summary>
        public static string MESSAGE_HISTORY {
            get {
                return ResourceManager.GetString("MESSAGE_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear History 的本地化字符串。
        /// </summary>
        public static string MESSAGE_HISTORY_CLEAR {
            get {
                return ResourceManager.GetString("MESSAGE_HISTORY_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        public static string MESSAGE_SEND {
            get {
                return ResourceManager.GetString("MESSAGE_SEND", resourceCulture);
            }
        }
    }
}
